config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'static_pages#home'
  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :places, only: [ :index ]
      resources :medicines, only: [ :index ]
    end # v1
    namespace :v2 do
      resources :places, only: [ :index ]
      resources :medicines, only: [ :index ]
    end # v1
  end # api
end

app/views/layouts/_user_header.html.erb
<ul class="nav nav-pills pull-right">
  <% if user_signed_in? %>
    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carta SESA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

  <body cz-shortcut-listen="true">
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Carta SESA</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <%= form_for(:user, url: session_path(:user), :html => {class:"navbar-form navbar-right"} ) do |f| %>
              <div class="form-group">
                <%= f.email_field :email, placeholder: "Email", autofocus: true, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.password_field :password, placeholder: "Senha", autocomplete: "off", class: "form-control" %>
              </div>
                <%= f.submit "Entrar", class: "btn btn-success" %>
                  <%= link_to "Cadastrar", new_registration_path(:user), class: "btn btn-primary" %>
            <% end %>

          </div><!--/.navbar-collapse -->
        </div>
      </nav>

      <div class="container">
        <div class="row">
            <%= yield %>
        </div>
      </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>


</body>
</html>